import { pgTable, text, serial, integer, boolean, timestamp, varchar, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Import Auth Models
export * from "./models/auth";

// Enums
export const attendanceEnum = pgEnum("attendance", ["attending", "maybe", "not_attending"]);

// Guests Table
export const guests = pgTable("guests", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  phoneNumber: text("phone_number").notNull(),
  attendance: attendanceEnum("attendance").notNull(),
  totalPax: integer("total_pax").default(1),
  wishes: text("wishes"),
  luckyDrawCode: text("lucky_draw_code").unique().notNull(),
  isWinner: boolean("is_winner").default(false),
  winRank: integer("win_rank"), // 1 for 1st prize, etc.
  createdAt: timestamp("created_at").defaultNow(),
});

// Schemas
export const insertGuestSchema = createInsertSchema(guests).omit({ 
  id: true, 
  createdAt: true,
  luckyDrawCode: true, // Generated by backend
  isWinner: true, 
  winRank: true 
});

// Types
export type Guest = typeof guests.$inferSelect;
export type InsertGuest = z.infer<typeof insertGuestSchema>;
