import { pgTable, text, serial, integer, boolean, timestamp, varchar, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Import Auth Models
export * from "./models/auth";

// Enums
export const attendanceEnum = pgEnum("attendance", ["attending", "maybe", "not_attending"]);

// Guests Table
export const guests = pgTable("guests", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  phoneNumber: text("phone_number").notNull(),
  attendance: attendanceEnum("attendance").notNull(),
  totalPax: integer("total_pax").default(1),
  wishes: text("wishes"),
  luckyDrawCode: text("lucky_draw_code").unique().notNull(),
  isWinner: boolean("is_winner").default(false),
  winRank: integer("win_rank"), // 1 for 1st prize, etc.
  createdAt: timestamp("created_at").defaultNow(),
});

// Settings Table
export const settings = pgTable("settings", {
  id: serial("id").primaryKey(),
  eventName: text("event_name").notNull().default("Rumah Terbuka & Akikah"),
  eventNameLine2: text("event_name_line2"),
  familyName: text("family_name").notNull().default("Keluarga Hj. Ahmad & Hjh. Sarah"),
  familyIntro: text("family_intro"),
  eventDate: text("event_date").notNull().default("Sabtu, 25 Nov 2024"),
  eventTime: text("event_time").notNull().default("11:00 PG - 4:00 PTG"),
  locationName: text("location_name").notNull().default("Dewan Seri Kenangan, KL"),
  googleMapsUrl: text("google_maps_url").notNull().default("https://maps.google.com"),
  wazeUrl: text("waze_url").notNull().default("https://waze.com"),
  heroImageUrl: text("hero_image_url").notNull().default("https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=2000&auto=format&fit=crop"),
  musicUrl: text("music_url"),
  musicTitle: text("music_title"),
  footerText: text("footer_text").notNull().default("© 2024 Majlis Akikah & Rumah Terbuka"),
  luckyDrawEnabled: boolean("lucky_draw_enabled").notNull().default(true),
});

// Program Table
export const programItems = pgTable("program_items", {
  id: serial("id").primaryKey(),
  time: text("time").notNull(),
  activity: text("activity").notNull(),
  order: integer("order").notNull().default(0),
});

// Schemas
export const insertGuestSchema = createInsertSchema(guests).omit({ 
  id: true, 
  createdAt: true,
  luckyDrawCode: true, // Generated by backend
  isWinner: true, 
  winRank: true 
});

export const insertSettingsSchema = createInsertSchema(settings).omit({ id: true });
export const insertProgramItemSchema = createInsertSchema(programItems).omit({ id: true });

// Types
export type Guest = typeof guests.$inferSelect;
export type InsertGuest = z.infer<typeof insertGuestSchema>;
export type Settings = typeof settings.$inferSelect;
export type InsertSettings = z.infer<typeof insertSettingsSchema>;
export type ProgramItem = typeof programItems.$inferSelect;
export type InsertProgramItem = z.infer<typeof insertProgramItemSchema>;
